services:
  postgres:
    image: postgres:17
    container_name: hyperbaric-postgres
    environment:
      POSTGRES_DB: hyperbaric
      POSTGRES_USER: hyperbaric_admin
      POSTGRES_PASSWORD: hyperbaric_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hyperbaric-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hyperbaric_user -d hyperbaric"]
      interval: 30s
      timeout: 10s
      retries: 3

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    container_name: hyperbaric-dragonfly
    ports:
      - "6379:6379"
    volumes:
      - dragonfly_data:/data
    networks:
      - hyperbaric-network
    restart: unless-stopped
    command: ["dragonfly", "--logtostderr", "--alsologtostderr"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  dragonfly_data:
    driver: local

networks:
  hyperbaric-network:
    driver: bridge
