packages:
  - "apps/**/*"
  - "packages/*"

catalogs:
  react:
    react: ^18.2.0
    react-dom: ^18.2.0
    "@types/react": ^18.2.43
    "@types/react-dom": ^18.2.17
    react-router-dom: ^6.26.2

  build:
    typescript: ^5.5.4
    "@types/node": ^24.0.0
    vite: ^5.0.8
    "@vitejs/plugin-react": ^4.2.1

  backend:
    hono: ^4.9.1
    "@hono/vite-dev-server": ^0.20.1
    better-auth: ^1.3.13
    kysely: ^0.28.7
    pg: ^8.16.3
    "@types/pg": ^8.15.5
    dotenv: ^17.2.1

  ui:
    "@heroicons/react": ^2.2.0

  testing:
    vitest: ^3.2.4
    "@testcontainers/postgresql": ^11.6.0
    testcontainers: ^11.6.0

  mdx:
    "@mdx-js/react": ^3.0.1
    "@mdx-js/rollup": ^3.0.1
    remark-frontmatter: ^5.0.0
    remark-mdx-frontmatter: ^4.0.0

  storybook:
    "@storybook/addon-docs": ^9.1.3
    "@storybook/addon-links": ^9.1.3
    "@storybook/react": ^9.1.3
    "@storybook/react-vite": ^9.1.3
    storybook: ^9.1.3
    serve: ^14.2.1
